CREATE TABLE Vendedor (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
codigo VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Cobrança (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
codigo VARCHAR(255) NOT NULL UNIQUE,
valor_original DECIMAL(19, 2) NOT NULL
);
